const ALL_JAVASCRIPT_BASICS_SOLUTIONS = require("./Javascript-Basics/index");
const ALL_JAVASCRIPT_PRACTICE_SOLUTIONS = require("./Javascript-Practice/index");
const ALL_JAVASCRIPT_DOM_SOLUTIONS = require("./Javascript-DOM/index");
const ALL_SOLUTIONS = [...ALL_JAVASCRIPT_BASICS_SOLUTIONS, ...ALL_JAVASCRIPT_PRACTICE_SOLUTIONS, ...ALL_JAVASCRIPT_DOM_SOLUTIONS];
module.exports = ALL_SOLUTIONS;