const ALL_JAVASCRIPT_DOM_SOLUTIONS = require("./Javascript-DOM/index");
const ALL_JAVASCRIPT_FUNDAMENTALS_SOLUTIONS = require("./Javascript-Fundamentals/index");
const ALL_SOLUTIONS = [...ALL_JAVASCRIPT_FUNDAMENTALS_SOLUTIONS, ...ALL_JAVASCRIPT_DOM_SOLUTIONS];
module.exports = ALL_SOLUTIONS;